---
- name: create a user
  hosts: ansibleclients
  become: true
  become_user: root
  tasks:
  - name: create a user
    ansible.builtin.user:
      name: tom4
      comment: tom4
      uid: 1040
    register: var
  - name: output debug
    debug: msg={{var}}
