---
- name: Create User
  hosts: ansibleclients
  become: yes  # Run tasks with sudo or become the root user

  vars:
    username: john2
    password: 'Nksdfh$1234'
    become_password: 'Nkwen2021$'  # Add your become password here

  tasks:
    - name: Ensure user exists
      user:
        name: "{{ username }}"
        password: "{{ password | default(omit) }}"
        state: present
      become_password: "{{ become_password }}"
