---
- name: Example Playbook with Sudo Password
  hosts: ansibleclients
  become: yes
  become_method: sudo
  become_user: root

  vars:
    sudo_password: 'Nkwen2021$'

  tasks:
    - name: Ensure user exists
      user:
        name: john10
        password: 'Nksdfh$1234'
        state: present
      become: yes
      become_pass: "{{ sudo_password }}"
