---
- name: create a user
  hosts: ansibleclients
  become: true
  become_pass: 'Nkwen2021$'
  tasks:
  - name: create a user
    ansible.builtin.user:
      name: anton
      comment: anton
      uid: 1040
    register: var
  - name: output debug
    debug: msg={{var}}
