--- 
- name: enable fw ports
  hosts: allprod
  become: yes

  tasks:
   - name: enable ports on redhat
     when: "ansible_distribution == 'RedHat'"
     firewalld:
        port: 900/tcp
        permanent: true
        state: enabled
     notify: relaod firewalld

   - name: enable ports on ubuntu
     when: "ansible_distribution == 'Ubuntu'"
     ufw:
      rule: allow
      port: 900
      proto: tcp
     notify: Reload ufw

  handlers:

    - name: relaod firewalld
      systemd: 
        name: firewalld
        state: restarted

    - name: Reload ufw
      service:
        name: ufw
        state: restarted
