---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.168.1.171
      username: administrator@vsphere.local
      password: Nkwen2021$
      validate_certs: False
      name: testm12
      template: vmtemplate
      datacenter: pdc
      folder: prodvms
      state: poweredon
      wait_for_ip_address: no
